# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update IP file

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main.py
      run: |
        python main.py

    - name: Configure Git
      run: |
        git config --global user.name "zhumouren"
        git config --global user.email "zhumouren0623@qq.com"

    - name: Add files to Git staging area
      run: |
        ls
        pwd
        git add .

    - name: Check Git status
      run: |
        git branch -a
        git remote -v
        git status

    - name: Commit changes
      run: |
        (
        git commit -m "Update ip files"
        ) || true



    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKENS }}